Object.defineProperty(exports, "__esModule", { value: true });

/**
 * API_AUTHOR
 * 
 * Clase que contiene un ejemplo estático del JSON de la BD :
 * - @author
 */
exports.USER_Data = [
    {
        "idUser": 1,
        "nameUser": "root",
        "alias": "R",
        "password": "passsss",
        "access": 7,
        "firstName": "AnLibrary",
        "lastName": "App",
        "phone": 956789099,
        "telePhone": 654789632,
        "email": "anlibrary@gmail.com",
        "dateofBirth": "2019-01-01T00:00:00",
        "street": "C/Street",
        "cp": 41100,
        "population": "Coría del Río",
        "province1": "Andalucía",
        "country1": "España",
        "sex1": "H",
        "documentIdentify": "13539669N",
        "photo": ""
    },
    {
        "idUser": 2,
        "nameUser": "00",
        "alias": "U",
        "password": "00",
        "access": 0,
        "firstName": "Nuser",
        "lastName": "Zero",
        "phone": 0,
        "telePhone": 896848466,
        "email": "testnar2.018@gmail.com",
        "dateofBirth": "2018-12-15T00:00:00",
        "street": "C/Madurez",
        "cp": 42140,
        "population": "Jerte",
        "province1": "Andalucia",
        "country1": "España",
        "sex1": "M",
        "documentIdentify": "02533669P",
        "photo": ""
    },
    {
        "idUser": 3,
        "nameUser": "02",
        "alias": "U",
        "password": "02",
        "access": 2,
        "firstName": "Nadmin",
        "lastName": "Admin Admin",
        "phone": 659895623,
        "telePhone": 955123456,
        "email": "testnar2018@gmail.com",
        "dateofBirth": "1998-08-08T00:00:00",
        "street": "C/Huelva,18",
        "cp": 54100,
        "population": "Coría del Rio",
        "province1": "Extremadura",
        "country1": "España",
        "sex1": "H",
        "documentIdentify": "77803565W",
        "photo": "Adidas.jpg"
    },
    {
        "idUser": 4,
        "nameUser": "01",
        "alias": "N",
        "password": "01",
        "access": 1,
        "firstName": "Nuser",
        "lastName": "One",
        "phone": 648569563,
        "telePhone": 954895623,
        "email": "t.estnar2018@gmail.com",
        "dateofBirth": "2018-08-16T00:00:00",
        "street": "C/Alemania",
        "cp": 51100,
        "population": "Vallecas",
        "province1": "Madrid",
        "country1": "España",
        "sex1": "H",
        "documentIdentify": "75895652Y",
        "photo": ""
    },
    {
        "idUser": 5,
        "nameUser": "nar18",
        "alias": "U",
        "password": "123",
        "access": 2,
        "firstName": "Nicolás",
        "lastName": "Alarcón",
        "phone": 561656565,
        "telePhone": 991616156,
        "email": "test.nar2018@gmail.com",
        "dateofBirth": "2018-12-13T00:00:00",
        "street": "C/Ucrania",
        "cp": 41100,
        "population": "Puerto Rico",
        "province1": "Madrid",
        "country1": "España",
        "sex1": "M",
        "documentIdentify": "02533663M",
        "photo": ""
    }
];
